#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

banner "News Polar Analysis — Render + Vercel deploy"

# Local .env already holds DATABASE_URL / OPENAI_API_KEY; we only ever read
# them to print for copy-paste into a dashboard, never send them anywhere.
_local_env_value() {
  [[ -f "$ENV_FILE" ]] || return 1
  grep -E "^${1}=" "$ENV_FILE" | tail -n1 | cut -d= -f2-
}

# ── Stage 1: Render — deploy the API blueprint ─────────────────────────────
stage "Render — deploy the API"
say "render.yaml is already in the repo root and defines the free web service"
say "for src/api/app.py. This stage creates the actual Render service from it."
open_url "https://dashboard.render.com/blueprints"
step "Click 'New Blueprint Instance' and connect/select the repo:"
note "  shakedarazi/News_Polar_Analysis"
step "Render will detect render.yaml and list its env vars. Three are marked"
step "'sync: false' and need to be filled in by hand — copy these from your"
step "local .env (printed below, for your eyes only, not sent anywhere):"
printf '\n'
db_val=$(_local_env_value DATABASE_URL || true)
if [[ -n "$db_val" ]]; then
  printf '  %sDATABASE_URL%s   = %s\n' "$BOLD" "$RESET" "$db_val"
else
  warn "DATABASE_URL not found in $ENV_FILE — grab it from your Neon dashboard instead."
fi
warn "OPENAI_API_KEY on Render must be a real OpenAI key (sk-...), NOT the"
warn "OpenRouter key in your local .env. The two workloads use separate keys:"
note "  Render (site AI: qa/summarize/bias) → real OpenAI key"
note "  GitHub Actions (ingestion: classify) → OpenRouter key"
note "See rotate_openai_key_wizard.sh to set up or rotate the Render one."
printf '\n'
note "render.yaml deliberately declares no OPENAI_BASE_URL / OPENAI_MODEL —"
note "their absence routes the API to api.openai.com. Don't add them here."
step "For CORS_ORIGINS, paste a placeholder for now (e.g. http://localhost:3000)"
step "— you'll update it to the real Vercel URL in stage 4."
pause "Filled in DATABASE_URL, OPENAI_API_KEY, and CORS_ORIGINS in Render? Press Enter."
step "Click 'Apply' / 'Create Blueprint' to trigger the first deploy."
pause "Deploy kicked off? Press Enter once it's building."

# ── Stage 2: capture + verify the Render URL ────────────────────────────────
stage "Render — capture the live URL"
say "Render assigns a URL like https://news-polar-api.onrender.com once the"
say "service is up. Free-tier builds can take a few minutes — wait for the"
say "dashboard to show 'Live' before continuing."
ask RENDER_URL "Paste the Render service URL:"
write_env RENDER_URL "$RENDER_URL"
say "Checking $RENDER_URL/api/health ..."
if command -v curl >/dev/null 2>&1; then
  if curl -fsS --max-time 15 "${RENDER_URL%/}/api/health" >/dev/null 2>&1; then
    printf '  %s✓ healthy%s — API is responding.\n' "$GREEN" "$RESET"
  else
    warn "no response yet — free-tier services cold-start slowly. Retry later with:"
    note "  curl ${RENDER_URL%/}/api/health"
  fi
else
  warn "curl not found — check ${RENDER_URL%/}/api/health manually in a browser."
fi

# ── Stage 3: Vercel — deploy the frontend ───────────────────────────────────
stage "Vercel — deploy the frontend"
say "The Next.js app lives in frontend/, not the repo root — this is the"
say "single most common mistake when importing this repo into Vercel."
open_url "https://vercel.com/new"
step "Import the repo:"
note "  shakedarazi/News_Polar_Analysis"
warn "CRITICAL: in 'Configure Project', set Root Directory to: frontend"
step "Under Environment Variables, add:"
note "  NEXT_PUBLIC_API_URL = ${RENDER_URL}"
pause "Root Directory set to 'frontend' and NEXT_PUBLIC_API_URL added? Press Enter."
step "Click 'Deploy'."
pause "Deploy finished? Press Enter once Vercel shows the live preview."
ask VERCEL_URL "Paste the Vercel deployment URL:"
write_env VERCEL_URL "$VERCEL_URL"

# ── Stage 4: wire CORS back up + final verification ────────────────────────
stage "Final verification"
say "Now that the frontend URL is known, lock down CORS on the API side."
open_url "https://dashboard.render.com"
step "Open the news-polar-api service → Environment → edit CORS_ORIGINS:"
note "  ${VERCEL_URL}"
step "Save — this triggers a redeploy (~1-2 min)."
pause "CORS_ORIGINS updated and redeploy finished? Press Enter."
say "Re-checking $RENDER_URL/api/health ..."
if command -v curl >/dev/null 2>&1 && curl -fsS --max-time 15 "${RENDER_URL%/}/api/health" >/dev/null 2>&1; then
  printf '  %s✓ healthy%s\n' "$GREEN" "$RESET"
else
  warn "couldn't confirm automatically — check ${RENDER_URL%/}/api/health manually."
fi
open_url "$VERCEL_URL"
step "Confirm the site loads and article data appears (open browser dev tools →"
step "Network/Console tabs — there should be no CORS errors on API calls)."
confirm "Frontend loads and successfully pulls data from the API?" \
  && printf '  %s✓ deploy verified end to end%s\n' "$GREEN" "$RESET" \
  || warn "note what failed — CORS_ORIGINS mismatch is the most common culprit."

finish
