#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=5

# Launched by double-click or `open -a Terminal`, the new window starts in the
# user's home directory — so anchor to the repo before touching .env,
# render.yaml, or git.
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# This wizard deliberately never reads, prompts for, or stores the new OpenAI
# key. It travels from your clipboard straight into the Render dashboard, so it
# never lands in this terminal's scrollback, in .env, or in shell history.

REPO_SLUG="shakedarazi/News_Polar_Analysis"
RENDER_SERVICE="news-polar-api"
DEFAULT_RENDER_URL="https://news-polar-api.onrender.com"

banner "News Polar Analysis — finish the two-key split on Render"

# ── Stage 1: confirm Render is deploying the branch that has the split ──────
stage "Repo — confirm main has the split"
say "The code side of this is already done and merged. main carries commit"
say "69652e5, which gives each workload its own distinctly named variables:"
printf '\n'
printf '  %ssite AI%s   qa / summarize / bias, on demand, on Render\n' "$BOLD" "$RESET"
note "    OPENAI_API_KEY            real OpenAI key   (dashboard)"
note "    OPENAI_MODEL              gpt-4o-mini       (from render.yaml)"
note "    OPENAI_BASE_URL           must not exist    → api.openai.com"
printf '\n'
printf '  %singestion%s  classify, every 6h, on GitHub Actions\n' "$BOLD" "$RESET"
note "    OPENAI_INGESTION_API_KEY  OpenRouter key    (from the GitHub secret)"
note "    OPENAI_INGESTION_BASE_URL https://openrouter.ai/api/v1"
note "    OPENAI_INGESTION_MODEL    openai/gpt-4o-mini"
printf '\n'
say "Because the names differ, nothing can silently cross over — there is no"
say "fallback from one key to the other in src/nlp/openai_config.py."
printf '\n'
if git rev-parse --git-dir >/dev/null 2>&1; then
  note "current branch: $(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '?')"
  git fetch -q origin main 2>/dev/null || true
  if git show origin/main:src/nlp/openai_config.py 2>/dev/null | grep -q 'OPENAI_INGESTION_API_KEY'; then
    printf '  %s✓%s origin/main has the two-key config.\n' "$GREEN" "$RESET"
  else
    warn "origin/main does NOT look like it has the split — stop and check."
  fi
  if git show origin/main:render.yaml 2>/dev/null | grep -q 'OPENAI_BASE_URL'; then
    warn "origin/main's render.yaml still declares OPENAI_BASE_URL — stop."
  else
    printf '  %s✓%s origin/main render.yaml declares no OPENAI_BASE_URL.\n' "$GREEN" "$RESET"
  fi
else
  warn "not a git repo here — run this wizard from the repo root."
fi
printf '\n'
warn "Render's blueprint must be deploying from main. If it tracks another"
warn "branch, the old single-key render.yaml wins and undoes stage 3."
pause "Render is deploying from main? Press Enter."

# ── Stage 2: paste the new key into Render ──────────────────────────────────
stage "Render — paste the new OpenAI key"
open_url "https://dashboard.render.com"
step "Open the ${RENDER_SERVICE} service → Environment."
step "Edit OPENAI_API_KEY and paste the new real OpenAI key (starts sk-...)."
printf '\n'
warn "Paste it into the browser only — never into this terminal."
warn "Do NOT paste the OpenRouter key (sk-or-v1-...) here. That one stays in"
warn "GitHub and reaches the runner as OPENAI_INGESTION_API_KEY."
printf '\n'
note "If you don't have write access to this service, the Render account owner"
note "has to do this stage — Hobby-plan services can't be shared per-service."
note "Check nobody else is editing the same service right now."
pause "New OpenAI key pasted into OPENAI_API_KEY? Press Enter."

# ── Stage 3: leave OPENAI_MODEL alone; only OPENAI_BASE_URL must go ─────────
stage "Render — clear OPENAI_BASE_URL & redeploy"
say "Only one variable has to disappear. Its absence is what routes the SDK"
say "to api.openai.com."
printf '\n'
step "Still in ${RENDER_SERVICE} → Environment:"
printf '\n'
printf '  %sDELETE%s  OPENAI_BASE_URL   %s(if present — was openrouter.ai/api/v1)%s\n' \
  "$RED" "$RESET" "$DIM" "$RESET"
printf '  %sKEEP%s    OPENAI_MODEL      %smust read exactly: gpt-4o-mini%s\n' \
  "$GREEN" "$RESET" "$DIM" "$RESET"
printf '\n'
warn "OPENAI_MODEL is NOT deleted — render.yaml provisions it on purpose. But"
warn "if it still reads 'openai/gpt-4o-mini' (the OpenRouter id), fix it to"
warn "the bare 'gpt-4o-mini' or OpenAI will reject every call."
printf '\n'
note "Leave DATABASE_URL, CORS_ORIGINS and PYTHON_VERSION alone."
pause "OPENAI_BASE_URL gone and OPENAI_MODEL = gpt-4o-mini? Press Enter."
step "Save changes. Render redeploys automatically; if not, use Manual Deploy."
pause "Redeploy finished and the service shows 'Live'? Press Enter."

# ── Stage 4: verify the site key actually works ─────────────────────────────
stage "Verify — the site's AI features"
ask RENDER_URL "Render service URL [${DEFAULT_RENDER_URL}]:"
[[ -z "${RENDER_URL:-}" ]] && RENDER_URL="$DEFAULT_RENDER_URL"
write_env RENDER_URL "$RENDER_URL"
base="${RENDER_URL%/}"

if ! command -v curl >/dev/null 2>&1; then
  warn "curl not found — skipping automated verification."
  SKIPPED+=("verify ${base}/api/health and a summary/generate call by hand")
else
  say "Waking the service (free tier cold-starts can take ~60s)..."
  if curl -fsS --max-time 120 "${base}/api/health" >/dev/null 2>&1; then
    printf '  %s✓ healthy%s\n' "$GREEN" "$RESET"
  else
    warn "no health response — the service may still be booting."
  fi

  say "Fetching one article id to test against..."
  article_id=$(curl -fsS --max-time 120 "${base}/api/articles?limit=1" 2>/dev/null \
    | python3 -c 'import sys,json; print(json.load(sys.stdin)["items"][0]["article_id"])' 2>/dev/null || true)

  if [[ -z "$article_id" ]]; then
    warn "couldn't read an article id — verify by hand once the API is awake."
    SKIPPED+=("POST ${base}/api/articles/<id>/summary/generate to confirm the key")
  else
    note "article: ${article_id:0:16}..."
    say "Calling summary/generate — the real proof: it forces a live OpenAI"
    say "call with the key you just pasted."
    body=$(mktemp)
    code=$(curl -sS --max-time 180 -o "$body" -w '%{http_code}' \
      -X POST "${base}/api/articles/${article_id}/summary/generate" 2>/dev/null || echo "000")
    printf '\n'
    case "$code" in
      200)
        printf '  %s✓ 200 — the new key works. The site half is live.%s\n' "$GREEN" "$RESET"
        ;;
      401|403)
        warn "HTTP $code — the key was rejected. Check you pasted the OpenAI key"
        warn "(sk-...) and not the OpenRouter one."
        head -c 300 "$body"; printf '\n'
        ;;
      502)
        warn "HTTP 502 — the API reached a provider but the call failed. Two"
        warn "usual causes: OPENAI_BASE_URL survived in the dashboard, or"
        warn "OPENAI_MODEL still reads 'openai/gpt-4o-mini'. Re-check stage 3."
        head -c 400 "$body"; printf '\n'
        ;;
      000)
        warn "no response within 180s — free-tier cold start or a hung request."
        ;;
      *)
        warn "HTTP $code — unexpected. Response:"
        head -c 400 "$body"; printf '\n'
        ;;
    esac
    rm -f "$body"
  fi
fi

# ── Stage 5: confirm the ingestion half still routes to OpenRouter ──────────
stage "Verify — ingestion still on OpenRouter"
say "The GitHub secret is still named OPENAI_API_KEY, but the workflow injects"
say "it into the runner as OPENAI_INGESTION_API_KEY — so the name on GitHub"
say "does not need to change, and nothing there should be edited."
printf '\n'
if git show origin/main:.github/workflows/ingestion.yml 2>/dev/null \
   | grep -q 'OPENAI_INGESTION_API_KEY: ${{ secrets.OPENAI_API_KEY }}'; then
  printf '  %s✓%s workflow maps secrets.OPENAI_API_KEY → OPENAI_INGESTION_API_KEY\n' "$GREEN" "$RESET"
else
  warn "couldn't confirm that mapping in origin/main's workflow — check it."
fi
printf '\n'
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  say "Secrets currently set on ${REPO_SLUG}:"
  gh secret list --repo "$REPO_SLUG" 2>/dev/null | sed 's/^/    /' || warn "couldn't list secrets"
  printf '\n'
  note "gh cannot read a secret's value — only you can confirm OPENAI_API_KEY"
  note "there is still the OpenRouter key (sk-or-v1-...). Leave it as is."
else
  open_url "https://github.com/${REPO_SLUG}/settings/secrets/actions"
  step "Confirm OPENAI_API_KEY is still set (it holds the OpenRouter key)."
fi
printf '\n'
if confirm "Trigger an ingestion run now to prove that half still works?"; then
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh workflow run ingestion.yml --repo "$REPO_SLUG" --ref main >/dev/null 2>&1; then
      printf '  %s✓ dispatched%s on main — watch it here:\n' "$GREEN" "$RESET"
      note "  gh run watch --repo $REPO_SLUG"
      note "  the 'Classification' section of the log is the OpenRouter path"
    else
      warn "dispatch failed — trigger it from the Actions tab instead."
    fi
  else
    open_url "https://github.com/${REPO_SLUG}/actions/workflows/ingestion.yml"
    step "Use 'Run workflow' to dispatch it manually."
  fi
else
  note "fine — the next scheduled run (every 6h) will exercise it anyway."
fi
pause "Done? Press Enter for the summary."

finish
